Accounts/urls.py
from django.urls import path
from .views import *

# from ..check_valid.check_information import *
app_name='Accounts'

urlpatterns=[
    #authenticated
    path('login_register',ShowFormLoginRegisterView.as_view(),name='login_register'),
    path('login',LoginView.as_view(),name='login'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('register',RegisterView.as_view(),name='register'),
    path('verify_otp_code',OtpCodeView.as_view(),name='otp'),


        # #resetpassword
    path('password/reset/',PasswordResetView.as_view(),name='passwordreset'),
    path('password/reset/done',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/',PasswordResetConfirm.as_view(),name='password_reset_confirm'),
    path('password/reset/complate',PasswordResetComplateView.as_view(),name='password_reset_complate'),
    
    path('contact',ContactView.as_view(),name='contact'),
    path('quastion',QuestionsView.as_view(),name='quastion'),
    path('answer',Answer_QuestionsView.as_view(),name='answer'),
    path('profile',UserProfileView.as_view(),name='profile'),
    path('check/information/',Check_Information_View.as_view(),name='emailexist'),




   

    


]

Beautiful_Princess/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Accounts/',include( 'Accounts.urls',namespace='Accounts')),
    path('',include( 'Category.urls',namespace='Category')),
    path('Option/',include( 'Product_option.urls',namespace='Option')),
    path('Orders/',include( 'Orders.urls',namespace='Orders')),



]

Orders/urls.py
from django.urls import path
from .views import *

app_name = 'Orders'
urlpatterns=[
    path('cart/view',CartView.as_view(),name='cart_view'),

    path('cart/add_and_remove',Cart_Add_and_remove_View.as_view(),name='cart_add'),
    path('pay_type',PayTypeView.as_view(),name='paytype'),

    path('cart/checkout',CheckOutView.as_view(),name='checkout'),
    path('copon',CoponView.as_view(),name='copon'),
    path('orders',OrderView.as_view(),name='orders'),
    path('archive/orders',Archive_Order_view.as_view(),name='archive_orders'),
    path('cart/list/item',Add_Product_To_Cart_Kesho.as_view(),name='archive_orders'),




    
    

]

Accounts/models.py
# from django.db import models

# # Create your models here.


from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .manager import MyUserManager


# # Create your models here.
# #coustom user model
class User(AbstractBaseUser):
    email = models.EmailField(max_length=200,unique=True)
    username = models.CharField(max_length=50,unique=True)
    phone = models.CharField(max_length=13,unique=True)
    address = models.CharField(max_length=500,blank=True)
    name =  models.CharField(max_length=50)
    family =  models.CharField(max_length=50)
    image = models.ImageField(upload_to='poster/')
    is_superuser = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    objects = MyUserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS =('email','phone')

    def __str__(self) -> str:
        return self.email
    
    def has_perm(self,perm,obj=None):
        return True
    
    def has_module_perms(self,app_label):
        return True
    
    @property
    def is_staff(self):
        return self.is_admin

    def all_like_me_count(self):
        return self.like_product.all().count()

    def get_ful_name(self):
        return f'{self.name}  {self.family}'

   
        
# #send sms for register not working in now
class OtpCodeModel(models.Model):
    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    code = models.CharField(max_length=500,null=True)
    created = models.DateTimeField(auto_now_add=True)

class QuestionModel(models.Model):
    name = models.CharField(max_length=50)
    que= models.CharField(max_length=500)
    answer = models.CharField(max_length=500,null=True)




# class NotifacationModel(models.Model):
#     user = models.ForeignKey(User,models.CASCADE,related_name='usernoti')
#     text = models.CharField(max_length=500,null=True)
#     view = models.BooleanField(default=False)


    

Accounts/forms.py
from django import forms
from .models import User
from utils.check_valid.check_information import Check_Email,check_username ,check_phone
# from django.contrib.auth.forms import ReadOnlyPasswordHashField

class UsercreateForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput,required=False)
    password2 = forms.CharField(widget=forms.PasswordInput,required=False)

    class Meta:
        model = User
        fields = ('email','username','phone')
    
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 !=password2:
            raise forms.ValidationError('password not math')
        if len(password2) < 7:
            raise forms.ValidationError('password not 8 ')

        return password1
    
    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise forms.ValidationError('email airly exist')
        if Check_Email(email):
            return email
        raise forms.ValidationError('email airly exist')
    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()
        if user:
            raise forms.ValidationError('username airly exist')
        if check_username(username):
            return username
        raise forms.ValidationError('username airly exist')
    def clean_phone(self):
        phone = self.cleaned_data['phone']
        user = User.objects.filter(phone=phone).exists()
        if user==False:
            if check_phone(phone):
                return phone
        raise forms.ValidationError('phone airly exist','ss')
        
    
    def save(self, commit= False):

        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user
    



# class UserChangeForm(forms.ModelForm):
#     password = ReadOnlyPasswordHashField()

#     class Meta:
#         model = User
#         fields = []


class UserLoginForm(forms.Form):
    email = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50)

# class UserRegisterForm(forms.Form):
#     username = forms.CharField(max_length=50)
#     email = forms.EmailField(max_length=50)

#     phone = forms.CharField(max_length=13)
#     password1 = forms.CharField(max_length=200)
#     password2 = forms.CharField(max_length=200)

    

Accounts/views.py
from django.shortcuts import render
from django.views import View
from django.http import  JsonResponse ,HttpResponse
from .forms import UserLoginForm , UsercreateForm
from django.contrib.auth import login,logout,authenticate
from django.shortcuts import render ,redirect
from django.contrib import messages
from .models import User , OtpCodeModel
from django.contrib.auth import views as auth_view
from django.urls import reverse_lazy
from random import randint
from utils.hash import hash_code
from utils.send_email import send_email_for_register
from .models import QuestionModel
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.



# from secrets import choice
# 
# from django.conf import settings

# 

# # from category.models import OrderModel
# # 
# 
# from .models import CompanyModel, User , OtpCodeModel
# from random import randint
# from django.core.mail import send_mail
# 
# 
# import string
# from comment.models import CommentModel, ReplayCommentModel
import time


# Create your views here.


class ShowFormLoginRegisterView(View):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('Category:home')
        return super().dispatch(request, *args, **kwargs)

    def get(Self,request):
        return render(request,'Accounts/login_register.html')
    



class LoginView(LoginRequiredMixin,View):
 
    def post(self,request):
        form =UserLoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd['email'].lower()
            password = cd['password']
            user = authenticate(request,username=username , password=password)
            
            if user is not None:
                code = str(randint(10000,99999))
                send_email_for_register(user.email,str(code))
                otp = OtpCodeModel.objects.filter(user=user)
                if otp.exists():
                    otp.delete()
                OtpCodeModel.objects.create(user=user,code=hash_code(code))
                request.session['user'] = {
                'email':username,
                'password':password,
                
            }
                return render(request,'Accounts/otpcode.html')
                
            else:
                return JsonResponse({'login':'user_not_found'})
        else:
            if form.errors:
                print('sss')
            return JsonResponse({'login':'form_not_valid'})

class LogoutView(View):
    def get(self ,request):
        logout(request)
        messages.success(request,'شما با موفقیت خارج شدید','success')
        return redirect('Accounts:login_register')






class OtpCodeView(View):
    def post(self,request):
        email= request.session['user']['email']
        password = request.session['user']['password']
        user = authenticate(request,username=email,password=password)
        
        otp = OtpCodeModel.objects.get(user=user)
        if str(otp.code) == hash_code(request.POST['otpcode']):
            otp.delete()
            login(request,user)
            return JsonResponse({'status_login':'login'})
        return JsonResponse({'status_login':'no_login'})


class RegisterView(View):
    def post(self,request):
        form = UsercreateForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            email = cd['email'].lower()
            username = cd['username'].lower()
            phone = cd['phone']
            password = cd['password1']
            User.objects.create_user(email=email,username=username,phone=phone,password=password)
            return JsonResponse({'register':'user_register'})
        else:
            lst_err = list(form.errors.as_data().keys())
            return JsonResponse({'register':'form_error','error':lst_err})
            
           



class PasswordResetView(auth_view.PasswordResetView):
    template_name = 'Accounts/reset/password_reset.html'
    email_template_name = 'Accounts/reset/email.html'
    success_url=reverse_lazy('Accounts:password_reset_done')
    
    print(email_template_name)





class PasswordResetDoneView(auth_view.PasswordResetDoneView):
    template_name = 'Accounts/reset/password_reset_done.html'




class PasswordResetConfirm(auth_view.PasswordResetConfirmView):
    template_name='Accounts/reset/password_reset_confirm.html'
    success_url=reverse_lazy('Accounts:password_reset_complate')
    


class PasswordResetComplateView(auth_view.PasswordResetCompleteView):
    template_name = 'Accounts/reset/password_reset_complate.html'



class ContactView(View):
    def get(self,request):
        return render(request,'Accounts/contact_us.html')
    def post(self,request):
        cd = request.POST
        name = cd['txt_name']
        que = cd['txt_question']
        QuestionModel.objects.create(name=name,que=que)
        messages.success(request,'سوال شما ثبت شد و در اسرع وقت به آن پاسخ داده میشود و در بخش سوالات به نمایش گداشته میشود ','success')
        return redirect('Accounts:contact')

class QuestionsView(View):
    def get(self,request):
        question = QuestionModel.objects.all()
        return render(request,'Accounts/quastion.html',{'question':question})


class Answer_QuestionsView(View):
    def get(self,request):
        question = QuestionModel.objects.filter(answer__isnull=True)
        return render(request,'Accounts/answer.html',{'question':question})
    def post(self,request):
        question =QuestionModel.objects.get(id= request.POST['id'])
        question.answer = request.POST['answer']
        question.save()
        return JsonResponse({'id':request.POST['id']})


class UserProfileView(LoginRequiredMixin,View):
    def get(self,request):
        return render(request,'Accounts/profile.html')
    
    def post(self,request):
        info = request.POST
        user = User.objects.get(id = request.user.id)
        try:
            name = info['txt_name'].split(' ')[0]
            family = info['txt_name'].split(' ')[1]
            user.name = name
            user.family = family
            user.username = info['txt_username']
            user.email = info['txt_email']
            user.phone = info['txt_phone']
            user.address = info['txt_address']
            img = request.FILES['img']
            user.image = img

            user.save()
            if request.GET.get('next') =='orderview':
                return redirect('category:order')
            messages.success(request,'پروفایل شما با موفقیت تکمیل شد ','success')
            return redirect('Category:home')
        except:
            messages.success(request,'عملیات با خطا مواجه شد','success')
            return redirect('Accounts:profile')

        



class Check_Information_View(View):
    def post(self,request):
        txt_name = request.POST['txt_name']
        txt_value =  request.POST['txt_value']
        if txt_name == 'phone':
            if txt_value != request.user.phone:
                user = User.objects.filter(phone =txt_value ).exists()
                if user:
                    return JsonResponse({'phone_status':False})
            return JsonResponse({'phone_status':True})
        if txt_name == 'email':
            if txt_value != request.user.email:
                user = User.objects.filter(email =txt_value ).exists()
                if user:
                    return JsonResponse({'email_status':False})
            return JsonResponse({'email_status':True})
        if txt_name == 'username':
            if txt_value != request.user.username:
                user = User.objects.filter(username =txt_value ).exists()
                if user:
                    return JsonResponse({'username_status':False})
            return JsonResponse({'username_status':True})





# class NotifacationView(View):
#     def get(self,request):
#         myorders = OrderModel.objects.filter(usersender=request.user,view=False)
#         # for order in myorders:
#         #     order.view = True
#         #     order.save
#         return render(request,'accounts/noti.html',{'myorders':myorders})
#     def post(self,request):
#         idorder = request.POST.get('idorder')
#         iduser = request.POST.get('iduser')






# class NotificationsView(View):
#     def get(self,request):
#         comments = ReplayCommentModel.objects.filter(to_user = request.user.username,view=False)
#         comments_tag = CommentModel.objects.filter(to_user = request.user.username)
        
#         comments_view = ReplayCommentModel.objects.filter(to_user = request.user.username,view=True)
#         return render(request,'accounts/notifications.html',{'comments':comments,'comments_view':comments_view,'comments_tag':comments_tag})
    
#     def post(self,request):
#         comments = ReplayCommentModel.objects.filter(to_user = request.user.username)
#         for c in comments:
#             c.view =True
#             c.save()
#         return JsonResponse({'status':'ok'})

Accounts/templates/Accounts/answer.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'Accounts/css/login_register.css'%}" >
   
{% endblock %}
{% block title %}
    افزودن اسلاید 
{% endblock %}
{% block body %}

<div dir="rtl" class="animate__animated animate__fadeInDown" style="width: 80%; margin-left: auto; margin-right: auto; position: relative;top: 100px;margin-bottom: 150px;">
    {% for que in question %}
    <div id="que_{{que.id}}">
     <a id="que_{{que.id}}" class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-{{que.id}}" style="height: 65px; margin-bottom: 10px; padding: 0 30px;">
        <input  class="m-0" value="{{que.que}}">
         <i class="fa fa-angle-down text-dark"></i>
     </a>
     <nav class="collapse show navbar navbar-vertical navbar-light  align-items-center p-0 border border-top-0 border-bottom-0" id="navbar-{{que.id}}">
         <div class="navbar-nav w-100 overflow-hidden" >
             <div  style="text-align: start; display: flex; justify-content: space-between; " class="nav-item dropdown">
                
                 <input id="txt_que_{{que.id}}"  style=" width: 70%; color: black;" href=""  dir="rtl" data-id="" onclick="cat_change(this)" data-name="" class="nav-link" > 
                <a onclick="answer(this)" data-id="{{que.id}}" class="btn btn-primary" style="margin:20px;">ارسال</a>         
                 
             </div>
            
         </div>
     </nav>
    </div>
     {% endfor %}

</div>
{% endblock %}

{% block script %}



<script  src="{% static 'Accounts/js/answer.js'%}"></script>






{% endblock %}

Accounts/templates/Accounts/contact_us.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'Accounts/css/login_register.css'%}" >
    <link rel="stylesheet" href="{% static 'Accounts/css/contant_us.css'%}" >

   
{% endblock %}
{% block title %}
    صفحه ورود
{% endblock %}
{% block body %}






<div class="container-fluid pt-5 animate__animated animate__fadeInDown" style="top: 50px;position: relative;">
    <div class="sec-titile text-center mb-4">
        <span class="px-2">سوالات</span>
    </div>
    <div class="row px-xl-5">
        <div class="col-lg-7 mb-5" style="background-color: lightpink; padding: 10px;margin: 10px;">
            <div class="contact-form">
                <div id="success"></div>
                <form name="sentMessage" id="contactForm" novalidate="novalidate" action="" method="POST">
                    <div class="control-group">
                        <input  type="text" class="form-control text-right" id="txt_name"  name="txt_name" placeholder="نام شما" value="{{user.get_ful_name}}" required="required" data-validation-required-message="Please enter your name">
                        <p class="help-block text-danger"></p>
                    </div>
                  
                    <div class="control-group">
                        <textarea  class="form-control text-right" rows="6" id="txt_question" name="txt_question" placeholder="سوال" required="required" data-validation-required-message="Please enter your message"></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                    {% csrf_token %}
                    <div>
                        <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">ارسال
                            </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-5 mb-5 text-right">
            <h5 class="font-weight-semi-bold mb-3">اطلاعات فروشگاه</h5>
            <p> </p>
            <div class="d-flex flex-column mb-3">
                <h5 class="font-weight-semi-bold mb-3"> ارتباط با ما </h5>
                <p dir="rtl" class="mb-2" ><i class="fa fa-map-marker-alt text-primary ml-3"></i>اصفهان - حسن آباد جرقویه - خ امام حسین</p>
                <p dir="rtl" class="mb-2"><i class="fa fa-envelope text-primary ml-3"></i>beautyful@gmail.com</p>
                <p  class="mb-2 text-right">+98 9134303981<i class="fa fa-phone-alt text-primary ml-3"></i></p>
            </div>
           
        </div>
    </div>
</div>
{% endblock %}
{% block script %}




<script  src="{% static 'Accounts/js/login_register.js'%}"></script>


<script>
    document.getElementById('nav-content').classList.add('active')
</script>

{% endblock %}

Accounts/templates/Accounts/login_register.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'Accounts/css/login_register.css'%}" >
   
{% endblock %}
{% block title %}
    صفحه ورود
{% endblock %}
{% block body %}








<div id="main" class="main" style="top: 100px; position: relative; margin-bottom: 150px;" >  	
    <input type="checkbox" id="chk" aria-hidden="true" >
    
        <div class="signup">
            <form id="form_register">
                <label class="text-danger" for="chk" aria-hidden="true"> ثبت نام</label>
                <input type="text" name="txt_username" placeholder="نام کاربری  " required="">
                {% csrf_token %}
                <input type="email" name="txt_email" placeholder="ایمیل" required="">
                <input type="text" name="txt_phone" placeholder="شماره موبایل" required="">
                <input type="password" name="txt_password1" placeholder="رمز عبور" required="">
                <input type="password" name="txt_password2" placeholder="رمز عبور" required="">

                <a onclick="register_click(this)" class="btn btn-primary" >ثبت نام </a>
            </form>
        </div>

        <div class="login">
            <form id="form_login">
                <label for="chk" aria-hidden="true">ورود</label>
                <input id="txt_email" type="email" name="email" placeholder="ابمیل" required="">
                <input id="txt_password" type="password" name="" placeholder="رمز عبور" required="">
                <h5>رمز عبور را فراموش کرده ام؟<a href="{% url 'Accounts:passwordreset'%}">بازیابی رمز </a></h5>
                <p class="input" onclick="login_click(this)">ورود</p>
            </form>
        </div>
</div>
{% endblock %}

{% block script %}




<script  src="{% static 'Accounts/js/login_register.js'%}"></script>




{% endblock %}

Accounts/templates/Accounts/otpcode.html
<style>
@keyframes fadeIn {
	0% {
		transform: scale(0);
		opacity: 0.0;		
	}
	60% {
		transform: scale(1.1);	
	}
	80% {
		transform: scale(0.9);
		opacity: 1;	
	}	
	100% {
		transform: scale(1);
		opacity: 1;	
	}		
}
.signup{
	
   animation: fadeIn;
   animation-duration: 1s;
  }

</style>


<input type="checkbox" id="chk" aria-hidden="true">

<div class="signup">
    <form id="form_register">
        <label class="text-primary" for="chk" aria-hidden="true"> ثبت کد</label>
        <input type="text" name="txt_otpcode" id="txt_otpcode" placeholder="کد ارسال شده" required="">
        
        
        <a onclick="otpcode_click(this)" class="btn btn-primary" >ثبت  </a>
    </form>
</div>

Accounts/templates/Accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'Accounts/css/login_register.css'%}" >
   
{% endblock %}
{% block title %}
    صفحه ورود
{% endblock %}
{% block body %}

<div id="main" class="main animate__animated animate__fadeInDown" style="height: 650px; top: 80px; margin-bottom: 130px;">  	
    <input type="checkbox" id="chk" aria-hidden="true">

        <div class="signup">
            <form method="post" enctype="multipart/form-data" action="" id="form_register">
                <label class="text-primary" for="chk" aria-hidden="true"> پروفایل</label>
                <input  type="text" value="{{user.name}} {{user.family}}" name="txt_name" placeholder="نام   " required="">
                <input onchange="txt_change(this,'username')" onkeyup="txt_change(this,'username')" type="text" value="{{user.username}}" name="txt_username" placeholder="نام کاربری  " required="">
                {% csrf_token %}

                <input  type="email" onkeyup="txt_change(this,'email')" name="txt_email" value="{{user.email}}" placeholder="ایمیل" required="">
                <input onkeyup="txt_change(this,'phone')" onchange="txt_change(this,'phone')" type="text" value="{{user.phone}}" name="txt_phone" placeholder="شماره موبایل" required="">
                <textarea name="txt_address" id="" cols="10" style="height: 150px;"  rows="10">{{user.address}} </textarea>
                <input name="img" type="file" value="" style="height: 50px;">

                <button type="submit" class="btn btn-primary" > تایید </button>
            </form>
        </div>

      
</div>

{% endblock %}

{% block script %}




<script  src="{% static 'Accounts/js/profile.js'%}"></script>




{% endblock %}

Accounts/templates/Accounts/quastion.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
   


{% endblock %}
{% block title %}
     سوالات
{% endblock %}
{% block body %}
<div dir="rtl" class="animate__animated animate__fadeInDown" style="width: 80%; margin-left: auto; margin-right: auto; position: relative;top: 80px; margin-bottom: 130px;">
    {% for que in question %}
     <a class="btn shadow-none d-flex align-items-center justify-content-between bg-secondary text-white w-100" data-toggle="collapse" href="#navbar-{{que.id}}" style="height: 65px; margin-bottom: 10px; padding: 0 30px; border-radius: 25px;">
         <h5 class="m-0">{{que.que}} </h5>
         <i class="fa fa-angle-down text-dark"></i>
     </a>
     <nav class="collapse navbar navbar-vertical navbar-light bg-transparent  align-items-center mb-2" id="navbar-{{que.id}}">
         <div class="navbar-nav w-100 overflow-hidden" >
             <div  style="text-align: start; display: flex; justify-content: space-between;" class="nav-item dropdown">
                
                 <a  style="width: 100%;"   dir="rtl" data-id=""  data-name="" class="nav-link" > 
                    {% if que.answer %}
                    {{que.answer}}
                    {% else %}
                    در انتظار پاسخ
                    {% endif %}           
                 </a>
             </div>
            
         </div>
     </nav>
     {% endfor %}

 </div>
 

{% endblock %}

{% block script %}
<script>
    document.getElementById('nav-question').classList.add('active')
</script>
{% endblock %}