Accounts/urls.py
from django.urls import path
from .views import *

# from ..check_valid.check_information import *
app_name='Accounts'

urlpatterns=[
    #authenticated
    path('login_register',ShowFormLoginRegisterView.as_view(),name='login_register'),
    path('login',LoginView.as_view(),name='login'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('register',RegisterView.as_view(),name='register'),
    path('verify_otp_code',OtpCodeView.as_view(),name='otp'),


        # #resetpassword
    path('password/reset/',PasswordResetView.as_view(),name='passwordreset'),
    path('password/reset/done',PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/',PasswordResetConfirm.as_view(),name='password_reset_confirm'),
    path('password/reset/complate',PasswordResetComplateView.as_view(),name='password_reset_complate'),
    
    path('contact',ContactView.as_view(),name='contact'),
    path('quastion',QuestionsView.as_view(),name='quastion'),
    path('answer',Answer_QuestionsView.as_view(),name='answer'),
    path('profile',UserProfileView.as_view(),name='profile'),
    path('check/information/',Check_Information_View.as_view(),name='emailexist'),




   

    


]

Beautiful_Princess/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Accounts/',include( 'Accounts.urls',namespace='Accounts')),
    path('',include( 'Category.urls',namespace='Category')),
    path('Option/',include( 'Product_option.urls',namespace='Option')),
    path('Orders/',include( 'Orders.urls',namespace='Orders')),



]

Category/urls.py
from operator import ne
from django.urls import path
from .views import *

app_name='Category'

urlpatterns=[
    path('',CategoryView.as_view(),name='home'),
    path('details/<str:cat_slug>/<str:type_slug>/<str:brand_slug>/<str:product_slug>',ProductDetailsView.as_view(),name='datails'),
    path('search/<str:category_slug>/',SearchCategoryView.as_view(),name='search_category'),
    path('text_search/<str:text_search>',BoxSearchView.as_view(),name='box_search'),
    path('search/<str:category_slug>/<str:type_slug>',SearchCategoryView.as_view(),name='search_category'),

    path('search/<str:category_slug>/<str:type_slug>/<str:name_product>',SearchCategoryView.as_view(),name='search_product'),

    path('shop',ShopView.as_view(),name='shop'),
    path('type/products/',TypeProductView.as_view(),name='type_product'),
    path('like',LikeCategoryView.as_view(),name='like'),
    path('most_view',Most_View.as_view(),name='most_view'),
    path('add_slide',Add_Slide_View.as_view(),name='add_slide'),
    path('add',AddProductView.as_view(),name='add_product'),
    path('Category/choise',ChoiseView.as_view(),name='choise'),
   




   


    ]

Orders/urls.py
from django.urls import path
from .views import *

app_name = 'Orders'
urlpatterns=[
    path('cart/view',CartView.as_view(),name='cart_view'),

    path('cart/add_and_remove',Cart_Add_and_remove_View.as_view(),name='cart_add'),
    path('pay_type',PayTypeView.as_view(),name='paytype'),

    path('cart/checkout',CheckOutView.as_view(),name='checkout'),
    path('copon',CoponView.as_view(),name='copon'),
    path('orders',OrderView.as_view(),name='orders'),
    path('archive/orders',Archive_Order_view.as_view(),name='archive_orders'),
    path('cart/list/item',Add_Product_To_Cart_Kesho.as_view(),name='archive_orders'),




    
    

]

templates/inc/foother.html
<div dir="rtl" class="container-fluid bg-secondary text-dark mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div  class="text-right col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <a href="" class="text-decoration-none">
                <h1  class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-3">P</span>beauty-pranc</h1>
            </a>
            <p class="mr-3" style="font-size: 25px;">زیبا بمان. ما به شما کمک میکنیم تا از آنچه که هستید زیباتر به نظر برسید. به خودت اهمیت بده</p>
            <p class="mb-2 "><i class="fa fa-map-marker-alt text-primary mr-3"></i>اصفهان - خ جلفا</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>mahditaba2ee@gmail.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>09134303981</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4 text-right"> میابر</h5>
                    <div dir="ltr"  class="d-flex flex-column text-right justify-content-start">
                        <a  class="text-dark mb-2" href="{% url 'Category:home'%}"><i class="fa fa-angle-left mr-2"></i>صفحه اصلی</a>
                        <a class="text-dark mb-2" href="{% url 'Orders:cart_view' %}"><i class="fa fa-angle-left mr-2"></i>سبد خرید</a>
                        <a class="text-dark mb-2" href="{% url 'Category:type_product' %}"><i class="fa fa-angle-left mr-2"></i>دسته ها</a>
                        <a class="text-dark mb-2" href="{% url 'Category:most_view' %}"><i class="fa fa-angle-left mr-2"></i>بیشترین بازدید</a>
                        <a class="text-dark mb-2" href="{% url 'Accounts:contact' %}"><i class="fa fa-angle-left mr-2"></i>تماس با ما</a>
                        
                    </div>
                </div>

                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4 text-right">میانبر </h5>
                    <div dir="ltr"  class="d-flex flex-column text-right justify-content-start">
                        <a  class="text-dark mb-2" href="{% url 'Accounts:login_register' %}"><i class="fa fa-angle-left mr-2"></i> ثبت نام</a>
                        <a class="text-dark mb-2" href="{% url 'Orders:checkout' %}"><i class="fa fa-angle-left mr-2"></i>فاکتور شما</a>
                        <a class="text-dark mb-2" href="{% url 'Category:shop' %}"><i class="fa fa-angle-left mr-2"></i>فروشگاه</a>
                        <a class="text-dark mb-2" href="{% url 'Accounts:quastion'%}"><i class="fa fa-angle-left mr-2"></i>سوالات</a>
                        <a class="text-dark" aria-disabled="true"><i class="fa fa-angle-left mr-2"></i>( بزودی)همکاری</a>
                    </div>
                </div>
        
                <div class="col-md-4 mb-5">
                    <h5 class="font-weight-bold text-dark mb-4 text-right">ارتباط با سازنده سایت</h5>
                    <form action="">
                        <div class="form-group">
                            <input type="text" class="form-control border-0 py-4" placeholder="پیغام شما " required="required" />
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control border-0 py-4" placeholder=" شماره تماس"
                                required="required" />
                        </div>
                        <div>
                            <button class="btn btn-primary btn-block border-0 py-3" type="submit"> ارسال</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
   
    </div>
</div>

templates/inc/navbar.html
<div onload="" class="container-fluid animate__animated animate__fadeInTopLeft">
    <div class="row bg-secondary py-2 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center">
                <a class="text-dark" href="{% url 'Accounts:quastion'%}">سوالات</a>
                
                <span class="text-muted px-2">|</span>
                <a class="text-dark" href="{%url 'Accounts:contact'%}">پشتیبانی</a>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
              
                <a class="text-dark px-2" href="https://instagram.com/mahdi_tabatabaee_" target="_blank">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="text-dark px-2" href="https://telegram.org/mahdi_tabatabaee_" target="_blank">
                    <i class="fab fa-telegram"></i>
                </a>
                <a class="text-dark pl-2" href="https://whatsapp.com/mahdi_tabatabaee_" target="_blank">
                    <i class="fab fa-whatsapp"></i>
                </a>
            </div>
        </div>
    </div>
</div>


<div id="box-top-sec" class="row align-items-center py-3 px-xl-5 mx-auto  box-top-sec">
    <div class="col-lg-3 d-none d-lg-block">
        <a onclick="show_div_hidden()"  class="text-decoration-none">
            <h3 class="m-0 display-5"><span class="text-primary font-weight-bold border px-3 mr-1">P</span>Princess</h3>
        </a>
    </div>
    <div class="col-lg-6 col-6 text-left">
        <form method="GET" action="">
            <div class="input-group">
                <input style="border-radius: 25px;" value="{{text_search}}" type="text" class="form-control" dir="rtl" name="search" id="search" placeholder="جستجو(نام)">
                <div onclick="search_click()" class="input-group-append">
                    
                    <button type="button" style="height: 100%;  border: none;" class="input-group-text text-danger bg-transparent">
                        
                        <i  class="fa fa-search"></i>
                       
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-lg-3 col-6 text-right">
        <a href="{% url 'Category:like'%}" class="btn">
            <i id="like_icon" class="fas fa-heart {%if all_like_me_count != 0 %}text-danger{% endif %}"></i>
            <span id="len_like" class="badge">{{all_like_me_count}}</span>
        </a>
        <a onclick="hiden_kesho_cart()"  class="btn ">
            <i id="shop_icon" class="fas fa-shopping-cart {%if len_cart != 0 %}text-danger{% endif %}"></i>
            <span id="len_cart" class="badge">{{len_cart}}</span>
        </a>
    </div>
</div>
 
<div class="container-fluid mb-5 animate__animated animate__fadeInTopRight">
    <div class="row border-top px-xl-5">
     
        <div class="col-lg-9 mx-auto">
            <nav style="top: 100px;" class="navbar  navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0 ">
                <a onclick="show_div_hidden()" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold px-3 mr-1">P</span>beauty</h1>
                </a>
                <button  dir="rtl" type="button" style="width: auto; border: none; outline: none;" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <h3  class="ml-1 mt-1 display-5"><span onclick="menu_icon_click(this)" class="text-primary font-weight-bold  px-3 mr-1 fa fa-chevron-down"></span>فهرست</h3>
                </button>
                <div class="collapse navbar-collapse justify-content-between text-right nav-btn" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0 ">
                        {% if user.is_authenticated %}
                        <a href="{% url 'Accounts:logout' %}" class="nav-item nav-link">خروج</a>
                        {% else %}
                        <a id="nav-lagin" href="{% url 'Accounts:login_register' %}" class="nav-item nav-link">ثبت نام و ورود </a>
                       {% endif %}
                    </div>
                    <div dir="rtl" class="navbar-nav mx-auto py-0">
                        <a href="{% url 'Category:home'%}" class="nav-item nav-link ">صفحه اصلی</a>
                        <a href="{% url 'Category:shop'%}" id="nav-shop" class="nav-item nav-link ">فروشگاه</a>
                        <a href="{% url 'Category:type_product'%}" id="nav-type" class="nav-item nav-link ">دسته بندی جزیی</a>
                        <div class="nav-item dropdown ">
                            <a id="nav-prodile" href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">پروفایل</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                <a href="{% url 'Orders:cart_view' %}" class="dropdown-item">کارت شما</a>
                                <a href="{% url 'Orders:checkout'%}" class="dropdown-item">فاکتور</a>
                                <a href="{% url 'Accounts:profile'%}" class="dropdown-item"> پروفایل</a>
                            </div>
                        </div>
                        <a href="{%url 'Accounts:contact'%}" id="nav-content" class="nav-item nav-link ">تماس با ما</a>
                        <a href="{% url 'Accounts:quastion'%}" id="nav-question" class="nav-item nav-link ">سوالات متداول  </a>
                        <!-- <a id="nav-question" class="nav-item nav-link ">
                            <div class="form-check form-switch">
                            <input onchange="dark()" class="form-check-input" style="font-size: 20px;" type="checkbox" id="mySwitch" name="darkmode" value="yes">
                            <label class="form-check-label mr-5" for="mySwitch">حالت شب</label>
                          </div>  </a> -->
                        


                        
                    {% if user.is_admin %}
                    <div class="nav-item dropdown">
                        <a id="nav-order" href="#" class="nav-link dropdown-toggle " data-toggle="dropdown">سبدها</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="{% url 'Orders:orders' %}" class="dropdown-item">در حال انتظار</a>
                            <a href="{% url 'Orders:archive_orders'%}" class="dropdown-item">تایید شده</a>
                           

                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a id="nav-add" href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">افزودن</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="{% url 'Category:add_slide'%}" class="dropdown-item">افزودن اسلایدر</a>
                            <a href="{% url 'Category:add_product'%}" class="dropdown-item"> افزودن کالا</a>
                            <a href="{% url 'Accounts:answer'%}" class="dropdown-item"> افزودن پاسخ</a>

                        </div>
                    </div>
                    {% endif %}





                    </div>
                   
                </div>
            </nav>
           

            </div>
        </div>
    </div>
</div>